baseURL = "https://loveyyp1314.github.io/"
title = "{CodeTrace} - Discover Issues, Share Solutions."
languageCode = "en-us"
theme = "Niello"
staticDir = ["themes/Niello/static", "static"]

# 确保没有任何 [languages] 的字样

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 1
# ... 其他菜单项 ...

[params]
# ... 您的 params ...

[outputs]
  home = ["HTML", "JSON"]
