baseURL = "https://loveyyp1314.github.io/"
# 将 title 直接放在顶层
title = "{CodeTrace} - Discover Issues, Share Solutions."
# 设置默认语言
languageCode = "en-us"
# 主题和静态目录保持不变
theme = "Niello"
staticDir = ["themes/Niello/static", "static"]

# 删除了整个 [languages] 部分！

# 将菜单简化为单语言模式
[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 1
[[menu.main]]
  name = 'Categories'
  pageRef = '/categories'
  weight = 2
[[menu.main]]
  name = 'Tags'
  pageRef = '/tags'
  weight = 3
[[menu.main]]
  name = 'Contact'
  pageRef = '/contact'
  weight = 4

# params 部分保持不变
[params]
[params.google]
google_ad_client = "ca-pub-******"
ga4 = "G-******"
[params.bannershowcase]
categories = ["AI"]
limit = 2
[params.email]
contact = "angularcorp@outlook.com"
[params.ignore]
categories = ["privacy", "terms", "archives", "cookie"]
[params.license]
copyright = "&#xA9; 2019 ~ 2025 by guangmean. All Rights Reserved."
[params.share]
sharethis = "******"
[params.disqus]
shortname = "******"

[outputs]
  home = ["HTML", "JSON"]
